# Generated by Django 4.2.4 on 2023-09-06 03:19

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transaction', '0002_change_date_fields_to_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltransactioncategory',
            name='user',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transactioncategory',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historicaltransaction',
            name='transaction_date',
            field=models.DateField(default=datetime.datetime(2023, 9, 6, 3, 18, 44, 128352, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_date',
            field=models.DateField(default=datetime.datetime(2023, 9, 6, 3, 18, 44, 128352, tzinfo=datetime.timezone.utc)),
        ),
    ]
