# Generated by Django 4.2.4 on 2023-09-06 03:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0003_add_user_field_to_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltransactioncategory',
            name='transaction_type',
            field=models.CharField(choices=[('IN', 'Income'), ('EX', 'Expense')], default='EX', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transactioncategory',
            name='transaction_type',
            field=models.CharField(choices=[('IN', 'Income'), ('EX', 'Expense')], default='EX', max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historicaltransaction',
            name='transaction_date',
            field=models.DateField(default=datetime.datetime(2023, 9, 6, 3, 37, 0, 627975, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_date',
            field=models.DateField(default=datetime.datetime(2023, 9, 6, 3, 37, 0, 627975, tzinfo=datetime.timezone.utc)),
        ),
    ]
