# Generated by Django 4.2.4 on 2023-09-06 03:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0004_add_transaction_type_field_to_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltransaction',
            name='transaction_date',
            field=models.DateField(default=datetime.datetime(2023, 9, 6, 3, 42, 21, 313337, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='historicaltransactioncategory',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='historicaltransactioncategory',
            name='transaction_type',
            field=models.CharField(choices=[('IN', 'Income'), ('EX', 'Expense')], default='EX', max_length=2),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_date',
            field=models.DateField(default=datetime.datetime(2023, 9, 6, 3, 42, 21, 313337, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='transactioncategory',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='transactioncategory',
            name='transaction_type',
            field=models.CharField(choices=[('IN', 'Income'), ('EX', 'Expense')], default='EX', max_length=2),
        ),
    ]
